plugins {
	id 'java-library'
	id 'maven-publish'
}

group = 'it.orz'
version = '1.0.0'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(21)
	}
	withSourcesJar()
	withJavadocJar()
}

repositories {
	mavenCentral()
}

dependencies {
	api 'io.projectreactor:reactor-core:3.7.6'
	implementation 'org.slf4j:slf4j-api:2.0.17'

	testImplementation platform('org.junit:junit-bom:5.12.2')
	testImplementation 'org.junit.jupiter:junit-jupiter'
	testImplementation 'io.projectreactor:reactor-test:3.7.6'
	testImplementation 'org.assertj:assertj-core:3.27.3'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
	testRuntimeOnly 'ch.qos.logback:logback-classic:1.5.18'
}

tasks.named('test') {
	useJUnitPlatform()
}

publishing {
	publications {
		mavenJava(MavenPublication) {
			from components.java
		}
	}
}
